/// Flutter icons MyFlutterApp
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'RoShamBo';

  static const IconData hand_grab_o = const IconData(0xf255, fontFamily: _kFontFam);
  static const IconData hand_paper_o = const IconData(0xf256, fontFamily: _kFontFam);
  static const IconData hand_scissors_o = const IconData(0xf257, fontFamily: _kFontFam);
  static const IconData hand_lizard_o = const IconData(0xf258, fontFamily: _kFontFam);
  static const IconData hand_spock_o = const IconData(0xf259, fontFamily: _kFontFam);
  static const IconData question_circle_o = const IconData(0xf29c, fontFamily: _kFontFam);
}
